# Generated by Django 4.1.4 on 2023-01-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unclebudget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="envelope",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
