# Generated by Django 4.0.4 on 2022-05-26 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unclebudget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unclebudget.envelope'),
        ),
    ]
