# Generated by Django 4.0.4 on 2022-05-28 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unclebudget', '0002_alter_envelope_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='envelope',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='unclebudget.envelope'),
            preserve_default=False,
        ),
    ]
