# Generated by Django 4.2.7 on 2023-11-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unclebudget", "0002_envelope_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="envelope",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
