# Generated by Django 4.2.7 on 2023-11-25 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unclebudget", "0003_envelope_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="beginning_of_time",
            field=models.DateField(default=datetime.date(1969, 12, 31)),
        ),
    ]
