# Generated by Django 4.0.6 on 2022-10-31 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unclebudget', '0003_item_envelope'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='start_date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
            preserve_default=False,
        ),
    ]
