# Generated by Django 4.0.6 on 2022-11-02 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unclebudget', '0004_account_initial_balance_account_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unclebudget.receipt'),
        ),
    ]
