# Generated by Django 4.0.6 on 2022-11-02 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unclebudget', '0005_alter_entry_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unclebudget.receipt'),
        ),
    ]
