# Generated by Django 4.2.7 on 2024-12-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unclebudget", "0005_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="expected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="expected",
            field=models.BooleanField(default=False),
        ),
    ]
