# Generated by Django 4.0.6 on 2022-11-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unclebudget', '0007_receipt_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='balanced',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
