# Generated by Django 5.1.4 on 2024-12-27 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unclebudget", "0007_remove_item_expected"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="small_change_envelope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="unclebudget.envelope",
            ),
        ),
        migrations.AddField(
            model_name="userdata",
            name="small_change_threshold",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=9),
        ),
    ]
