# Generated by Django 5.1.4 on 2024-12-27 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unclebudget", "0008_userdata_small_change_envelope_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="transfer_envelope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="unclebudget.envelope",
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="small_change_envelope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="unclebudget.envelope",
            ),
        ),
    ]
