services:
  unclebudget:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    env_file: env
    environment:
      UNCLEBUDGET_DB_FILE: /opt/unclebudget/data/db.sqlite3
    volumes:
      - unclebudget-data:/opt/unclebudget/data
      - unclebudget-static:/opt/unclebudget/www

  nginx:
    image: nginx
    depends_on:
      - unclebudget
    env_file: env
    # Unset env vars not needed by nginx
    environment:
      UNCLEBUDGET_DB_FILE:
      UNCLEBUDGET_SECRET_KEY:
      UNCLEBUDGET_TIMEZONE:
    ports:
      - ${UNCLEBUDGET_BIND-127.0.0.1:8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - unclebudget-static:/usr/share/nginx/html/static:ro


volumes:
  unclebudget-data:
  unclebudget-static:
